env: docker

server:
  port: 8080
  #backlog: 5
  #workers: 2
  #timeout: 5
services:
  b:
    endpoint: "http://server-b:8080"
tracing:
  zipkin:
    service: "helidon-service-a"
    protocol: "http"
    host: "zipkin"