global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
- job_name: 'prometheus'
  # Override the global default and scrape targets from this job every 5 seconds.
  scrape_interval: 5s
  target_groups:
  - targets: ['hero-service:8080']
    labels:
      group: 'hero_service'
  - targets: ['quote-service:8080']
      labels:
        group: 'quote_service'